In [10]:
import numpy as np

## 线性代数

## 数组乘法

>引子：不要关注它们是什么，看看它们做了什么。

### 点积/内积/数量积/标量积

**点积**

`np.dot`:

- 如果 a 和 b 是一维的，就是内积 `np.inner`
- 如果 a 和 b 是二维的，是矩阵乘法 `np.matmul or a @ b`
- 如果 a 或 b 任意一个是常量 `np.maltiply or a * b`
- 如果 a 是 N 维，b 是一维 `sump roduct`
- 如果 a 是 N 维，b 是 M 维 `dot(a, b)[i,j,k,m] = sum(a[i,j,:] * b[k,:,m])`

**内积**

`np.inner`: 一维数组向量的普通内积（无复数共轭），在更高维度上，是最后一个轴上的sum product。

- 对一维数组，就是元素乘积之和 `sum(a * b)
- 如果有一个是标量，那就是直接相乘
- 对多维数组，等于 `np.tensordot(a, b, axes=(-1, -1))`，对于某个具体的索引，就是相乘后在最后一个维度上求和 `inner(a, b)[i0,...,ir-2,j0,...,js-2] = sum(a[i0,...,ir-2,:]*b[j0,...,js-2,:])`

[数量积 - 维基百科，自由的百科全书](https://zh.wikipedia.org/wiki/%E7%82%B9%E7%A7%AF)

a和b都是一维：

In [451]:
a = np.array([1, 2, 4])
b = np.array([4, 5, 6])

In [452]:
np.dot(a, b), 1*4 + 2*5 + 4*6, np.inner(a, b), sum(a * b)

(38, 38, 38, 38)

a和b都是二维：

In [453]:
rng = np.random.default_rng(42)
a = rng.integers(0, 10, (3, 4))
b = rng.integers(0, 10, (3, 4))

In [454]:
np.inner(a, b)

array([[119,  71,  63],
       [126,  52,  98],
       [112,  86,  96]])

In [455]:
np.tensordot(a, b, axes=(-1, -1))

array([[119,  71,  63],
       [126,  52,  98],
       [112,  86,  96]])

In [456]:
a @ b.T

array([[119,  71,  63],
       [126,  52,  98],
       [112,  86,  96]])

In [457]:
np.matmul(a, b.T)

array([[119,  71,  63],
       [126,  52,  98],
       [112,  86,  96]])

a或b是常量：

In [458]:
a * 2

array([[ 0, 14, 12,  8],
       [ 8, 16,  0, 12],
       [ 4,  0, 10, 18]])

In [461]:
np.dot(a, 2)

array([[ 0, 14, 12,  8],
       [ 8, 16,  0, 12],
       [ 4,  0, 10, 18]])

In [459]:
np.multiply(a, 2)

array([[ 0, 14, 12,  8],
       [ 8, 16,  0, 12],
       [ 4,  0, 10, 18]])

In [460]:
np.inner(a, 2)

array([[ 0, 14, 12,  8],
       [ 8, 16,  0, 12],
       [ 4,  0, 10, 18]])

a是多维b是一维：

In [462]:
rng = np.random.default_rng(42)
a = rng.integers(0, 10, (2, 3, 4))
b = np.array([1, 2, 3, 4])

In [463]:
np.dot(a, b)

array([[48, 44, 53],
       [70, 47, 50]])

In [464]:
# 最后一个维度乘积和
np.inner(a, b)

array([[48, 44, 53],
       [70, 47, 50]])

In [465]:
np.tensordot(a, b, axes=(-1, -1))

array([[48, 44, 53],
       [70, 47, 50]])

In [466]:
np.sum(a*b, axis=-1)

array([[48, 44, 53],
       [70, 47, 50]])

In [467]:
a @ b

array([[48, 44, 53],
       [70, 47, 50]])

a是m维b是n维：

In [720]:
rng = np.random.default_rng(42)
a = rng.integers(0, 10, (2, 4, 3))
b = rng.integers(0, 10, (2, 3, 3))

In [721]:
# a 和 b 最后一个维度可以不一样，也就是最后一个维度是自由的
dab = np.dot(a, b)
dab.shape

(2, 4, 2, 3)

In [487]:
# dot(a, b)[i,j,k,m] = sum(a[i,j,:] * b[k,:,m])
dab[1,2,1,0], sum(a[1,2,:] * b[1,:,0])

(102, 102)

In [483]:
# a 和 b 最后一个维度必须一样
iab = np.inner(a, b)
iab.shape

(2, 4, 2, 3)

In [489]:
# inner(a, b)[i0,...,ir-2,j0,...,js-2] = sum(a[i0,...,ir-2,:]*b[j0,...,js-2,:])
iab[1,2,1,0], sum(a[1,2,:] * b[1,0,:])

(72, 72)

In [442]:
np.alltrue(iab == np.tensordot(a, b, axes=(-1, -1)))

True

In [449]:
np.alltrue(iab == dab), np.any(iab == dab)

(False, False)

### 叉积/外积/向量积


\begin{aligned}\mathbf {u\times v} &={\begin{vmatrix}u_{2}&u_{3}\\v_{2}&v_{3}\end{vmatrix}}\mathbf {i} -{\begin{vmatrix}u_{1}&u_{3}\\v_{1}&v_{3}\end{vmatrix}}\mathbf {j} +{\begin{vmatrix}u_{1}&u_{2}\\v_{1}&v_{2}\end{vmatrix}}\mathbf {k} \\&=(u_{2}v_{3}-u_{3}v_{2})\mathbf {i} -(u_{1}v_{3}-u_{3}v_{1})\mathbf {j} +(u_{1}v_{2}-u_{2}v_{1})\mathbf {k} \end{aligned}

只支持二维或三维，表示与u和v都垂直的向量。

[叉积 - 维基百科，自由的百科全书](https://zh.wikipedia.org/wiki/%E5%8F%89%E7%A7%AF)

In [546]:
# 二维
a = [1, 1]
b = [-1, 1]

In [551]:
# 向量积在二维中不起作用，因为返回的向量在二维之外
# 长度就是面积（根号2×根号2）
np.cross(a, b)

array(2)

In [566]:
# 行变多并不等于维度变多
rng = np.random.default_rng(42)
a = rng.integers(0, 10, (2, 2))
b = rng.integers(0, 10, (2, 2))
a, b

(array([[0, 7],
        [6, 4]]),
 array([[4, 8],
        [0, 6]]))

In [567]:
np.cross(a, b)

array([-28,  36])

In [568]:
np.cross([0,7], [4,8]), np.cross([6, 4], [0, 6])

(array(-28), array(36))

In [589]:
# 三维
a = [1, 2, 4]
b = [4, 5, 6]

In [590]:
2*6-4*5, -(1*6-4*4), 1*5-2*4

(-8, 10, -3)

In [591]:
# 与a和b都垂直的向量
np.cross(a, b)

array([-8, 10, -3])

还有几个关于维度的三参数，用于改变数组的定义（有点类似C和F Style）。

In [596]:
# 行变多并不等于维度变多
rng = np.random.default_rng(42)
a = rng.integers(0, 10, (2, 3))
b = rng.integers(0, 10, (2, 3))
a, b

(array([[0, 7, 6],
        [4, 4, 8]]),
 array([[0, 6, 2],
        [0, 5, 9]]))

In [600]:
np.cross(a, b)

array([[-22,   0,   0],
       [ -4, -36,  20]])

In [611]:
np.cross([0,7,6], [0,6,2]), np.cross([4,4,8], [0,5,9])

(array([-22,   0,   0]), array([ -4, -36,  20]))

In [627]:
np.cross(a, b, axisc=0)

array([[-22,  -4],
       [  0, -36],
       [  0,  20]])

In [628]:
a.T,b.T

(array([[0, 4],
        [7, 4],
        [6, 8]]),
 array([[0, 0],
        [6, 5],
        [2, 9]]))

In [630]:
np.cross(a.T, b.T)

array([ 0, 11, 38])

In [631]:
np.cross(a, b, axisa=0, axisb=0)

array([ 0, 11, 38])

In [633]:
np.cross([0,4], [0,0]), np.cross([7,4],[6,5]), np.cross([6,8], [2,9])

(array(0), array(11), array(38))

In [641]:
# 这个是实际计算时沿着的维度，和上面的不一样
np.cross(a, b, axis=0)

array([ 0, 11, 38])

### 张量积/外积

- [张量积 - 维基百科，自由的百科全书](https://zh.wikipedia.org/wiki/%E5%BC%A0%E9%87%8F%E7%A7%AF)
- [外积 - 维基百科，自由的百科全书](https://zh.wikipedia.org/wiki/%E5%A4%96%E7%A7%AF)

In [522]:
a = [1, 2, 4]
b = [4, 5, 6]

In [523]:
np.outer(a, b)

array([[ 4,  5,  6],
       [ 8, 10, 12],
       [16, 20, 24]])

In [524]:
rng = np.random.default_rng(42)
a = rng.integers(0, 10, (2, 3, 4))
b = rng.integers(0, 10, (2, 3, 4))

In [525]:
np.alltrue(
    np.outer(a,b) == a.ravel().reshape(24, 1) @ b.ravel().reshape(1, 24)
)

True

In [526]:
np.alltrue(np.outer(a, b) == np.tensordot(a.ravel(), b.ravel(), axes=((), ())))

True

### 矩阵乘法

`np.dot`上面已经提过了，其实还有个`np.matmul`和它很类似，但二者是有一些区别的。

- `dot`不是通函数，而`matmul`是通函数，也就意味这有通函数的一些通用参数
- `matmul`不支持向量和数字相乘
- `matmul`矩阵（好像元素一样）堆叠在一起广播

关于`np.matmul`：

- 如果都是二维，就是常规的矩阵乘法
- 如果任意个是多维（>2），则把它当成驻留在最后两个索引中的矩阵堆栈，并相应地广播
- 如果第一个是一维，则通过在其维度前面加上 1 来将其提升为矩阵，矩阵乘法后删除前面附加的 1
- 如果第二个是一维，则在维度上append 1，矩阵乘法后再删除后面附加的 1

二维的情况：

In [652]:
rng = np.random.default_rng(42)
a = rng.integers(0, 10, (2, 3))
b = rng.integers(0, 10, (3, 2))
a, b

(array([[0, 7, 6],
        [4, 4, 8]]),
 array([[0, 6],
        [2, 0],
        [5, 9]]))

In [653]:
np.matmul(a, b)

array([[44, 54],
       [48, 96]])

其中一个是一维的情况：

In [655]:
rng = np.random.default_rng(42)
a = rng.integers(0, 10, (2, 3))
b = rng.integers(0, 10, (3,))
a, b

(array([[0, 7, 6],
        [4, 4, 8]]),
 array([0, 6, 2]))

In [680]:
np.matmul(a, b), (a @ np.stack((b, [1, 1, 1]), axis=1))[:,0]

(array([54, 40]), array([54, 40]))

In [690]:
np.matmul(b, a.T), (np.stack(([1, 1, 1], b), axis=0) @ a.T)[1,:]

(array([54, 40]), array([54, 40]))

任意一个是多维：

In [723]:
rng = np.random.default_rng(42)
a = rng.integers(0, 10, (2, 3, 4, 5))
b = rng.integers(0, 10, (2, 3, 5, 9))

In [712]:
np.matmul(a, b).shape

(2, 3, 4, 9)

In [725]:
(a @ b).shape

(2, 3, 4, 9)

In [713]:
np.dot(a, b).shape

(2, 3, 4, 2, 3, 9)

In [702]:
np.alltrue(np.dot(a, b) == np.matmul(a, b))

True

看个简单点的例子：

In [728]:
rng = np.random.default_rng(42)
a = rng.integers(0, 10, (2, 3, 2))
b = rng.integers(0, 10, (2, 2, 2))

In [767]:
# 2x3x2
np.matmul(a, b)

array([[[49, 49],
        [70, 70],
        [84, 84]],

       [[48, 24],
        [10,  2],
        [97, 41]]])

In [739]:
a[0,:,:] @ b[0,:,:]

array([[49, 49],
       [70, 70],
       [84, 84]])

In [745]:
a[1,:,:] @ b[1,:,:]

array([[48, 24],
       [10,  2],
       [97, 41]])

In [761]:
# 2x3x2
np.matmul(a[0,:,:], b)

array([[[49, 49],
        [70, 70],
        [84, 84]],

       [[56, 28],
        [62, 22],
        [84, 36]]])

In [763]:
# 2x3x2
np.matmul(a[1,:,:], b)

array([[[42, 42],
        [14, 14],
        [98, 98]],

       [[48, 24],
        [10,  2],
        [97, 41]]])

看看dot是咋样表现的：

In [756]:
# 2x3x2x2
np.dot(a,b)

array([[[[49, 49],
         [56, 28]],

        [[70, 70],
         [62, 22]],

        [[84, 84],
         [84, 36]]],


       [[[42, 42],
         [48, 24]],

        [[14, 14],
         [10,  2]],

        [[98, 98],
         [97, 41]]]])

In [758]:
# 3x2x2
np.dot(a[0,:,:], b[:,:,:])

array([[[49, 49],
        [56, 28]],

       [[70, 70],
        [62, 22]],

       [[84, 84],
        [84, 36]]])

In [765]:
# 3x2x2
np.dot(a[1,:,:], b[:,:,:])

array([[[42, 42],
        [48, 24]],

       [[14, 14],
        [10,  2]],

       [[98, 98],
        [97, 41]]])

## Padding

Padding操作，参数如下：

- 数组
- pad_width：序列、整数或数组，每个轴边缘扩展的数量。
- 模式：默认constant。还包括：edge, linear_ramp, maximum, mean, median, minimum, reflect, symmetric, wrap, empty。
- stat_length：序列、整数或数组，模式是`maximum`, `minimum`, `mean`, `median`\时，用来计算每个轴边缘的值，默认None。
- constant_values：序列或标量，padding的值，默认0。
- end_values：虚列或标量，模式是`linear_ramp`时使用，用于结束值，经形成填充数组的边缘，默认0。
- reflect_type：模式是`reflect`和`symmetric`时使用，默认使用`even`风格，边缘值周围不改变反射，`odd`模式，数组的拓展部分是通过从边缘值的两倍中减去反射值来创建的。

首先看pad_width参数：

In [798]:
# tuple
np.pad(
    [1,2,3,4,5], 
    (2,3),  # 等于((2,3),), ((2,3))
    "constant", 
    constant_values=(4, 6)
)

array([4, 4, 1, 2, 3, 4, 5, 6, 6, 6])

In [805]:
np.pad(
    [1,2,3,4,5], 
    2, # 等于(2), (2, )
    "constant", 
    constant_values=(4, 6)
)

array([4, 4, 1, 2, 3, 4, 5, 6, 6])

In [809]:
# 分别左上，右下
np.pad(
    [[1,2,3],[4,5,6]],
    (1, 2)
)

array([[0, 0, 0, 0, 0, 0],
       [0, 1, 2, 3, 0, 0],
       [0, 4, 5, 6, 0, 0],
       [0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0]])

In [813]:
# 行（1,2）
# 列（2,1）
np.pad(
    [[1,2,3],[4,5,6]],
    ((1, 2), (2, 1))
)

array([[0, 0, 0, 0, 0, 0],
       [0, 0, 1, 2, 3, 0],
       [0, 0, 4, 5, 6, 0],
       [0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0]])

In [815]:
np.pad(
    [[1,2,3],[4,5,6]],
    1
)

array([[0, 0, 0, 0, 0],
       [0, 1, 2, 3, 0],
       [0, 4, 5, 6, 0],
       [0, 0, 0, 0, 0]])

接下来看下不同模式，顺带了解不同模式对应的额外参数。简单起见，`pad_width`我们统一使用整数。

In [816]:
a = np.arange(1, 7).reshape(3, 2)
a

array([[1, 2],
       [3, 4],
       [5, 6]])

In [817]:
# edge
np.pad(a, 1, "edge")

array([[1, 1, 2, 2],
       [1, 1, 2, 2],
       [3, 3, 4, 4],
       [5, 5, 6, 6],
       [5, 5, 6, 6]])

In [821]:
# linear_ramp
# 需要额外参数：end_values，默认0
np.pad(a, 1, "linear_ramp")

array([[0, 0, 0, 0],
       [0, 1, 2, 0],
       [0, 3, 4, 0],
       [0, 5, 6, 0],
       [0, 0, 0, 0]])

In [824]:
np.pad(a, 1, "linear_ramp", end_values=(1, ))

array([[1, 1, 1, 1],
       [1, 1, 2, 1],
       [1, 3, 4, 1],
       [1, 5, 6, 1],
       [1, 1, 1, 1]])

In [825]:
np.pad(a, 1, "linear_ramp", end_values=(1, 2), )

array([[1, 1, 1, 2],
       [1, 1, 2, 2],
       [1, 3, 4, 2],
       [1, 5, 6, 2],
       [1, 2, 2, 2]])

In [827]:
# 行（1,2）
# 列（3,4）
np.pad(a, 1, "linear_ramp", end_values=((1, 2), (3, 4)))

array([[3, 1, 1, 4],
       [3, 1, 2, 4],
       [3, 3, 4, 4],
       [3, 5, 6, 4],
       [3, 2, 2, 4]])

In [829]:
# 和这个等价
np.pad(
    a,
    1,
    "constant", 
    constant_values=((1, 2), (3,4))
)

array([[3, 1, 1, 4],
       [3, 1, 2, 4],
       [3, 3, 4, 4],
       [3, 5, 6, 4],
       [3, 2, 2, 4]])

In [832]:
# maximum, minmum, mean, median
# 需要额外参数stat_length，默认None，使用该轴所有值
np.pad(a, 1, "maximum")

array([[6, 5, 6, 6],
       [2, 1, 2, 2],
       [4, 3, 4, 4],
       [6, 5, 6, 6],
       [6, 5, 6, 6]])

In [837]:
# 只取2个
np.pad(a, 1, "maximum", stat_length=2)

array([[4, 3, 4, 4],
       [2, 1, 2, 2],
       [4, 3, 4, 4],
       [6, 5, 6, 6],
       [6, 5, 6, 6]])

In [844]:
# 分别取，左上2，右下1
np.pad(a, 1, "maximum", stat_length=((2, 1), ))

array([[4, 3, 4, 4],
       [2, 1, 2, 2],
       [4, 3, 4, 4],
       [6, 5, 6, 6],
       [6, 5, 6, 6]])

In [850]:
# 各自分别指定
# 行（2,1）
# 列（1,2）
np.pad(a, 1, "maximum", stat_length=((2, 1), (1, 2)))

array([[3, 3, 4, 4],
       [1, 1, 2, 2],
       [3, 3, 4, 4],
       [5, 5, 6, 6],
       [5, 5, 6, 6]])

In [858]:
b = a.astype(np.float16)

In [860]:
# mean和median类似
# 行（2,1）
# 列（1,2）
np.pad(b, 1, "mean", stat_length=((2, 1), (1, 2)))

array([[2. , 2. , 3. , 2.5],
       [1. , 1. , 2. , 1.5],
       [3. , 3. , 4. , 3.5],
       [5. , 5. , 6. , 5.5],
       [5. , 5. , 6. , 5.5]], dtype=float16)

In [870]:
a = [1,2,3,4,5]

In [883]:
# reflect, symmetric
# 需要额外参数reflect_type，默认even
# 首末是对称轴
np.pad(a, 3, "reflect")

array([4, 3, 2, 1, 2, 3, 4, 5, 4, 3, 2])

In [884]:
# 首末是对称轴
np.pad(a, 3, "reflect", reflect_type="odd")

array([-2, -1,  0,  1,  2,  3,  4,  5,  6,  7,  8])

In [885]:
# 边缘是对称轴
np.pad(a, 3, "symmetric")

array([3, 2, 1, 1, 2, 3, 4, 5, 5, 4, 3])

In [886]:
# 边缘是对称轴
np.pad(a, 3, "symmetric", reflect_type="odd")

array([-1,  0,  1,  1,  2,  3,  4,  5,  5,  6,  7])

In [889]:
# wrap
# 首尾互换
np.pad(a, 2, "wrap")

array([4, 5, 1, 2, 3, 4, 5, 1, 2])

In [900]:
# empty
# 未定义值扩展
np.pad(a, 1, "empty")

array([              0,               1,               2,               3,
                     4,               5, 123145302310976])

## 卷积

卷积函数（一维）遵循以下规则：

$$
(a * v)[n] = \sum_{m = -\infty}^{\infty} a[m] v[n - m]
$$

In [782]:
np.convolve([1, 2, 3], [0, 1, 0.5], "valid"), 0.5*1+1*2+0*3

(array([2.5]), 2.5)

In [783]:
np.convolve([1, 2, 3], [0, 1, 0.5], "same")

array([1. , 2.5, 4. ])

In [784]:
np.convolve([0, 1, 2, 3, 0], [0, 1, 0.5], "valid") 

array([1. , 2.5, 4. ])

In [785]:
# 默认 full
np.convolve([1, 2, 3], [0, 1, 0.5])

array([0. , 1. , 2.5, 4. , 1.5])

In [786]:
np.convolve([0, 0, 1, 2, 3, 0, 0], [0, 1, 0.5], "valid")

array([0. , 1. , 2.5, 4. , 1.5])

## 掩码运算