<h1>Table of Contents<span class="tocSkip"></span></h1>
<div class="toc"><ul class="toc-item"><li><span><a href="#认识NumPy" data-toc-modified-id="认识NumPy-1"><span class="toc-item-num">1&nbsp;&nbsp;</span>认识 NumPy</a></span><ul class="toc-item"><li><span><a href="#NumPy地位" data-toc-modified-id="NumPy地位-1.1"><span class="toc-item-num">1.1&nbsp;&nbsp;</span>NumPy 地位 </a></span></li><li><span><a href="#ndarray" data-toc-modified-id="ndarray-1.2"><span class="toc-item-num">1.2&nbsp;&nbsp;</span>ndarray</a></span></li><li><span><a href="#dtype" data-toc-modified-id="dtype-1.3"><span class="toc-item-num">1.3&nbsp;&nbsp;</span>dtype</a></span></li><li><span><a href="#shape" data-toc-modified-id="shape-1.4"><span class="toc-item-num">1.4&nbsp;&nbsp;</span>shape</a></span></li><li><span><a href="#向量化计算" data-toc-modified-id="向量化计算-1.5"><span class="toc-item-num">1.5&nbsp;&nbsp;</span>向量化计算 </a></span></li></ul></li></ul></div>

In [1]:
!pip3.8 show numpy

Name: numpy
Version: 1.22.3
Summary: NumPy is the fundamental package for array computing with Python.
Home-page: https://www.numpy.org
Author: Travis E. Oliphant et al.
Author-email: None
License: BSD
Location: /usr/local/lib/python3.8/site-packages
Requires: 
Required-by: xgboost, visualdl, tritonclient, transformers, torchvision, torch, tifffile, thinc, tf2onnx, tensorflow, tensorflow-probability, tensorflow-hub, tensorflow-datasets, tensorboardX, tensorboard, tensorbay, tensor2tensor, spacy, sox, sk-video, seqeval, seaborn, scipy, scikit-learn, scikit-image, scalene, scaitk, scainer, resampy, PyWavelets, pyFluidSynth, pyarrow, pretty-midi, pnlp, paramz, pandas, paddlepaddle, paddlefsl, opt-einsum, opencv-python, onnxruntime, onnx, numpy-quaternion, numba, note-seq, mir-eval, matplotlib, magenta, librosa, kfac, Keras-Preprocessing, jaxlib, jax, imageio, h5py, gym, GPyOpt, GPy, geneticalgorithm, dm-sonnet, bokeh, blis, akshare


In [1]:
import numpy as np

In [2]:
print(np.__version__)

1.22.3


## 认识NumPy

### NumPy地位

毫不夸张的说，NumPy 是数据科学/计算领域『最重要』的library，之前提到的Pandas，Scipy底层都用到了NumPy，而且，深度学习的各大框架也都用到了NumPy。更值得一提的是，这些框架的API和NumPy是一脉相承的，可以说NumPy熟练了，几个深度学习框架的不少API也同时学会了。

根据官方文档，主要特点包括：

- 强大的N维数组：矢量化、索引和广播概念快速且通用，是当今数组计算的事实标准。
- 数值计算工具：提供全面的数学函数，随机数生成器，线性代数例程，傅里叶变换等。
- 互操作性：支持广泛的硬件和计算平台，并且可以很好地与分布式，GPU和稀疏数组库配合使用。
- 性能强大：核心是经过良好优化的C代码。享受Python的灵活性和编译代码的速度。
- 易于使用：高级语法使得来自任何背景或经验水平的程序员都可以访问和高效产出。
- 开源：BSD协议（一个很宽松的协议，除了不能以NumPy的名义牟利，其他基本随意）。

### ndarray

NumPy 提供了一个 N 维数组类型，即 `ndarray`，描述了**相同类型**「元素」集合。它是「**偏底层的 array 接口**」。

所有的 `ndarray` 元素都是同质的，每个元素占用大小相同的内存块，具体大小由「数据类型」决定。`ndarray` 可以共享相同数据。

对象签名如下：

```python
numpy.ndarray(shape, dtype=float, buffer=None, offset=0, strides=None, order=None)
```

- shape：整数元组，表示形状
- dtype：数据类型对象
- buffer：使用 buffer 中的数据填充 `ndarray`
- offset：buffer 中的偏移量
- stride：内存中数据跨度
- order：行为主（C-Style）或列为主（Fortran-Style）


当 buffer 为空时，shape, dtype 和 order 三个参数会被使用；  
当 buffer 不为空时，所有参数都会被使用。

In [4]:
# buffer 为空，结果随机
arr = np.ndarray(shape=(2, 3), dtype=np.int, order="C")
arr

array([[ 0, 88,  0],
       [ 0,  0,  0]])

In [7]:
# buffer 不为空
buf = np.array([1, 2, 3, 4], dtype=np.int)
arr = np.ndarray(shape=(2, 2), 
                 dtype=np.int, 
                 buffer=buf)
arr

array([[1, 2],
       [3, 4]])

### dtype

NumPy内置了dtype类（数据类型对象），定义了NumPy的数据类型，比Python内置的数据类型要丰富很多。

总的来说可以大致分成以下几种，而我们绝大多数情况下最应该关注的其实就是 int 和 float 这两种：

- bool：`bool8`, `bool_`，不是 int
- int：`int8/byte`, `int16/short`, `int32`, `int64/longlong`, `int_`
- uint：无符号类型，表示 `unsigned`，对应 int
- float：`float16/half`, `float32/single`, `float64/double`, `float_`
- complex：复数，`complex64`, `complex128`, `complex_`
- str：`str0`, `str_`，表示 unicode 编码
- bytes: `bytes_`, `string_`
- datetime/timedelta
- structed array

后面的数字表示一个数字在内存中占几位，**一般比较推荐使用这种表示**；带下划线的表示 python 的数据类型，numpy 可以自动将 python 的类型转为它；此外，浮点数还支持不同精度以及扩展精度。

![](https://numpy.org/devdocs/_images/dtype-hierarchy.png)

In [9]:
# 直观验证上图的关系
(
    isinstance(np.str_(), np.flexible),
    isinstance(np.bytes_(), np.flexible),
    isinstance(np.void(b""), np.flexible),
    
    isinstance(np.int_(), np.integer),
    isinstance(np.float_(), np.floating),
    isinstance(np.complex_(), np.complexfloating)
)

(True, True, True, True, True, True)

In [15]:
# 很多类型都有 alias，它们其实是一回事
(
    np.short is np.int16, np.byte is np.int8,
    # 不同精度
    np.half is np.float16, np.single is np.float32, np.double is np.float64,
    # 扩展精度
    np.longfloat is np.longdouble,
    # 字符串
    np.unicode_ is np.str_,
    # bytes
    np.bytes_ is np.string_
)

(True, True, True, True, True, True, True, True)

In [17]:
# python 内置类型
(
    np.bool_ is np.bool8, 
    np.int_ is np.int64,
    np.float_ is np.float64,
    np.str_ is np.str0,
    np.complex_ is np.complex128
)

(True, True, True, True, True)

### shape

shape一般是个元组，表示数组的形状。

In [22]:
buf = np.arange(1, 9, dtype=np.int8)
buf

array([1, 2, 3, 4, 5, 6, 7, 8], dtype=int8)

In [23]:
bytes(buf)

b'\x01\x02\x03\x04\x05\x06\x07\x08'

In [26]:
# 改一下 shape
buf.shape = 2, 4
buf

array([[1, 2, 3, 4],
       [5, 6, 7, 8]], dtype=int8)

In [27]:
bytes(buf)

b'\x01\x02\x03\x04\x05\x06\x07\x08'

事实上，无论 shape 怎么变化，内存是完全没变化的，不同的 array 其实就是不同的 strides 方式而已。感兴趣的可以进一步阅读参考资料【2】。

另外，使用 buffer 创建的 ndarray 都使用了同一块内存。

In [31]:
arr1 = np.ndarray(
    shape=(2, 4), 
    dtype=np.int8, 
    buffer=buf)
arr1

array([[1, 2, 3, 4],
       [5, 6, 7, 8]], dtype=int8)

In [30]:
arr2 = np.ndarray(
    shape=(4, 2), 
    dtype=np.int8, 
    buffer=buf)
arr2

array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8]], dtype=int8)

In [33]:
bytes(arr1), bytes(arr2)

(b'\x01\x02\x03\x04\x05\x06\x07\x08', b'\x01\x02\x03\x04\x05\x06\x07\x08')

In [32]:
np.may_share_memory(arr1, arr2), np.may_share_memory(buf, arr1)

(True, True)

其实，无论 arr1 还是 arr2 都是 buf 的一个 view（引用），与此相对的是 copy。感兴趣的可以进一步阅读参考资料【2】。

### 向量化计算

NumPy的ndarray是同构的：数组只能包含一种类型的数据。在知道数组的内容在数据类型上是同构的时，NumPy能够将对数组内容执行数学运算的任务委托给C代码执行。此过程称为矢量化。这和Python的list不同，Python在迭代数组时必须仔细检查每个元素的数据类型。

如果不同类型，NumPy会自动匹配当前输入最合适的数据类型，并将其 cast 到所有元素。

In [42]:
# float+int
np.array([1, 2.0]).dtype

dtype('float64')

In [37]:
# string+int
np.array([1, "s"]).dtype

dtype('<U21')