<h1>Table of Contents<span class="tocSkip"></span></h1>
<div class="toc"><ul class="toc-item"><li><span><a href="#创建" data-toc-modified-id="创建-1"><span class="toc-item-num">1&nbsp;&nbsp;</span>创建 </a></span><ul class="toc-item"><li><span><a href="#np.arange" data-toc-modified-id="np.arange-1.1"><span class="toc-item-num">1.1&nbsp;&nbsp;</span>np.arange</a></span></li><li><span><a href="#reshape" data-toc-modified-id="reshape-1.2"><span class="toc-item-num">1.2&nbsp;&nbsp;</span>reshape</a></span></li><li><span><a href="#np.array" data-toc-modified-id="np.array-1.3"><span class="toc-item-num">1.3&nbsp;&nbsp;</span>np.array</a></span></li><li><span><a href="#np.ones/zeros" data-toc-modified-id="np.ones/zeros-1.4"><span class="toc-item-num">1.4&nbsp;&nbsp;</span>np.ones/zeros</a></span></li><li><span><a href="#np.full" data-toc-modified-id="np.full-1.5"><span class="toc-item-num">1.5&nbsp;&nbsp;</span>np.full</a></span></li><li><span><a href="#指定类型" data-toc-modified-id="指定类型-1.6"><span class="toc-item-num">1.6&nbsp;&nbsp;</span>指定类型 </a></span></li></ul></li><li><span><a href="#查看与选取" data-toc-modified-id="查看与选取-2"><span class="toc-item-num">2&nbsp;&nbsp;</span>查看与选取 </a></span><ul class="toc-item"><li><span><a href="#切片/索引" data-toc-modified-id="切片/索引-2.1"><span class="toc-item-num">2.1&nbsp;&nbsp;</span>切片 / 索引 </a></span></li><li><span><a href="#不规则切片/花式索引" data-toc-modified-id="不规则切片/花式索引-2.2"><span class="toc-item-num">2.2&nbsp;&nbsp;</span>不规则切片 / 花式索引 </a></span></li></ul></li><li><span><a href="#修改" data-toc-modified-id="修改-3"><span class="toc-item-num">3&nbsp;&nbsp;</span>修改 </a></span><ul class="toc-item"><li><span><a href="#拆分" data-toc-modified-id="拆分-3.1"><span class="toc-item-num">3.1&nbsp;&nbsp;</span>拆分 </a></span></li><li><span><a href="#合并" data-toc-modified-id="合并-3.2"><span class="toc-item-num">3.2&nbsp;&nbsp;</span>合并 </a></span></li><li><span><a href="#缺失值处理" data-toc-modified-id="缺失值处理-3.3"><span class="toc-item-num">3.3&nbsp;&nbsp;</span>缺失值处理 </a></span></li><li><span><a href="#修改形状" data-toc-modified-id="修改形状-3.4"><span class="toc-item-num">3.4&nbsp;&nbsp;</span>修改形状 </a></span></li><li><span><a href="#轴的调换" data-toc-modified-id="轴的调换-3.5"><span class="toc-item-num">3.5&nbsp;&nbsp;</span>轴的调换 </a></span></li><li><span><a href="#修改数据类型" data-toc-modified-id="修改数据类型-3.6"><span class="toc-item-num">3.6&nbsp;&nbsp;</span>修改数据类型 </a></span></li><li><span><a href="#拷贝" data-toc-modified-id="拷贝-3.7"><span class="toc-item-num">3.7&nbsp;&nbsp;</span>拷贝 </a></span></li><li><span><a href="#排序" data-toc-modified-id="排序-3.8"><span class="toc-item-num">3.8&nbsp;&nbsp;</span>排序 </a></span></li></ul></li></ul></div>

In [1]:
import numpy as np

## 创建

### np.arange

`np.arange` 与 Python 的 `range` 用法一样，都用来创建一维数组。

接口参数：`[start], stop, [step]`，方括号里的是可选参数，默认值分别是 0 和 1。

In [35]:
[v for v in range(10)]

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [9]:
# 只有 stop
np.arange(5)

array([0, 1, 2, 3, 4])

In [10]:
# 指定 start, stop
np.arange(2, 5)

array([2, 3, 4])

In [11]:
# 指定 start, stop, step
np.arange(2, 5, 2)

array([2, 4])

### reshape

如果我们想创建一个多维数组，则需要将刚刚创建的一维数组 `reshape` 成多维。  
`reshape` 中元素数量乘积（元素总数）必须与一维向量元素数量相等。


注：在线性代数中一般一维数组=向量；二维数组=矩阵；三维+数组=张量。

In [12]:
# reshape 成 2 行 5 列的二维数组
np.arange(10).reshape(2, 5)

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [13]:
# reshape 成 2×2×3 的三维数组
np.arange(12).reshape(2, 2, 3)

array([[[ 0,  1,  2],
        [ 3,  4,  5]],

       [[ 6,  7,  8],
        [ 9, 10, 11]]])

In [14]:
# reshape 的 shape 中数字的乘积（元素数量）必须与一维向量元素数量相等
np.arange(10).reshape(3, 3)

ValueError: cannot reshape array of size 10 into shape (3,3)

### np.array

创建 `ndarray` 的快捷接口，接受一个 object，可以是：

- 一个 List
- 一个 Tuple
- 一个 List 的 Tuple
- 一个嵌套的 List

In [16]:
# list
np.array([1, 2])

array([1, 2])

In [20]:
# tuple
np.array((1, 2))

array([1, 2])

In [18]:
# list tuple
np.array([
    (1, 2, 3),
    (4, 5, 6)
])

array([[1, 2, 3],
       [4, 5, 6]])

In [19]:
# list list
np.array([
    [1, 2, 3],
    [4, 5, 6]
])

array([[1, 2, 3],
       [4, 5, 6]])

### np.ones/zeros

快速创建全 1 或全 0 的数组，可以指定 `shape`。

注意：创建的数字默认是 `float` 类型。

In [22]:
np.ones((2, 2, 2))

array([[[1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.]]])

In [25]:
np.zeros((1, 3, 1, 3))

array([[[[0., 0., 0.]],

        [[0., 0., 0.]],

        [[0., 0., 0.]]]])

### np.full

快速创建一个给定 shape 和填充值的数组。

注意：给定的填充值 shape 需要与给定的 shape 对应。参数 `shape` 是一个 tuple。

In [44]:
# 最简单的，给定 fill 是一个值
np.full((2, 3), 2)

array([[2, 2, 2],
       [2, 2, 2]])

In [46]:
# 如果 fill 是一个向量，那长度必须和 shape 的最后一维相等
np.full((2, 3), [1, 2, 3]), np.full((1, 2, 3), [1, 2, 3])

(array([[1, 2, 3],
        [1, 2, 3]]),
 array([[[1, 2, 3],
         [1, 2, 3]]]))

In [53]:
# 否则会提示错误
try:
    np.full((2, 2), [1, 2, 3])
except Exception as e:
    print(e)

could not broadcast input array from shape (3,) into shape (2,2)


如果 fill 是多维数组：

- shape 必须在行或列上与给定的 shape 对应，另一个维度为 1
- 或者与给定 shape 完全一致

否则会提示上面的错误。

In [58]:
fill = [[4], [3]]
# 2 行
np.full((2, 3), fill), np.full((2, 2), fill)

(array([[4, 4, 4],
        [3, 3, 3]]),
 array([[4, 4],
        [3, 3]]))

In [59]:
fill = [[3, 4, 5]]
# 或者 3 列
np.full((2, 3), fill)

array([[3, 4, 5],
       [3, 4, 5]])

In [72]:
fill = [[1, 2, 3], [4, 5, 6]]
# 或者一致
np.full((2, 3), fill)

array([[1, 2, 3],
       [4, 5, 6]])

### 指定类型

一般创建数组时不需要指定类型。但如果需要制定，建议「显式」地指定。

In [68]:
# 指定为 int8 类型
np.array([2, 3], np.int8)

array([2, 3], dtype=int8)

In [61]:
# 指定为 float16 类型
np.arange(8, dtype=np.float16).reshape(2, 4)

array([[0., 1., 2., 3.],
       [4., 5., 6., 7.]], dtype=float16)

In [64]:
# 常见的整型
np.int8, np.int16, np.int32, np.int64

(numpy.int8, numpy.int16, numpy.int32, numpy.int64)

In [65]:
# 常见的浮点精度
np.float16, np.float32, np.float64

(numpy.float16, numpy.float32, numpy.float64)

## 查看与选取

In [64]:
arr = np.arange(1, 21, dtype=np.int32).reshape(5, 4)
arr

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16],
       [17, 18, 19, 20]], dtype=int32)

切片和索引是通过对已有 array 进行操作而得到想要的「部分」元素的行为过程。一般有两种方式：正下标和负下标，前者是从前往后的，后者是从后往前的。


切片/索引核心动作可以概括为：按维度根据不同维度的 index 对 array 进行操作，其中切片常通过 `start:stop:step` 操作，不处理的维度统一用 `:` 或 `...` 代替。

所以在看操作时，要首先关注「`,`」在哪里。要处理的维度和之前 `arange` `linspace` 等接口使用方法是一样的。


切片和索引有一些区别：

-  一般来说，索引（indexing）会创建 copy，切片（slicing）会创建 view。
- 切片表示法指定开始和结束值 [start：end]，并将列表从start复制到end-1。
- 索引返回数组的一个元素，切片返回一个元素的列表。

通俗点理解，切片一般都是有一个范围的，而索引看起来就是「摘取」某些元素。切片和索引经常会一起使用。实际使用时无须过多纠结。

### 切片/索引

In [91]:
# 正下标
# 第一行
arr[0]

array([1, 2, 3, 4], dtype=int32)

In [93]:
# 等价于
arr[0,:]

array([1, 2, 3, 4], dtype=int32)

In [95]:
# 负下标
# 最后一行
arr[-1]

array([17, 18, 19, 20], dtype=int32)

In [97]:
# 注意，这是个索引
arr[[0]]

array([[1, 2, 3, 4]], dtype=int32)

In [99]:
# 取某个元素是一个数字，此时不需要创建引用
a = arr[0, 1]
a

2

In [101]:
# 第一列
arr[:, 0]

array([ 1,  5,  9, 13, 17], dtype=int32)

In [103]:
# 最后一列
arr[:, -1]

array([ 4,  8, 12, 16, 20], dtype=int32)

In [105]:
# 然后带点范围 第 1-2 行
arr[0:3]

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]], dtype=int32)

In [107]:
# 等价于
arr[0:3, :]

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]], dtype=int32)

### 不规则切片/花式索引

In [87]:
arr

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16],
       [17, 18, 19, 20]], dtype=int32)

In [111]:
# 一个指定，一个范围，切片
arr[1, 2:5]

array([7, 8], dtype=int32)

In [115]:
# 还可以来点跳跃，步长：start:stop:step，第 1 行到第 4 行，间隔为 2，即第 1、3 行，切片
arr[1: 4: 2]

array([[ 5,  6,  7,  8],
       [13, 14, 15, 16]], dtype=int32)

In [118]:
# 加上列也可以哦，第 1、3 行，第 0、2 列，切片
arr[1:4:2, 0:3:2]

array([[ 5,  7],
       [13, 15]], dtype=int32)

In [119]:
# 这个是正常的索引
arr[[0], [1]]

array([2], dtype=int32)

In [121]:
# 离散也可以：第 1，3 行
arr[[0, 3]]

array([[ 1,  2,  3,  4],
       [13, 14, 15, 16]], dtype=int32)

In [125]:
# 再来一个维度
arr[[0, 3], 1:4]

array([[ 2,  3,  4],
       [14, 15, 16]], dtype=int32)

## 修改

### 拆分

`np.split`，接受三个参数：

- 给定的 array
- 要拆分的个数
- 拆分沿着的维度（即沿着哪个维度拆），或对「某个维度」进行拆分，0 表示列，1 表示行

In [127]:
a = np.arange(1, 17, dtype=np.int32).reshape(4, 4)
a

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]], dtype=int32)

In [128]:
# np.split(array, nparts)
# axis=0，沿着列拆分，对列进行拆分
np.split(a, 2)

[array([[1, 2, 3, 4],
        [5, 6, 7, 8]], dtype=int32),
 array([[ 9, 10, 11, 12],
        [13, 14, 15, 16]], dtype=int32)]

In [129]:
# axis=1，对行进行拆分
np.split(a, 2, 1)

[array([[ 1,  2],
        [ 5,  6],
        [ 9, 10],
        [13, 14]], dtype=int32),
 array([[ 3,  4],
        [ 7,  8],
        [11, 12],
        [15, 16]], dtype=int32)]

📢 特别注意：如果不满足拆分条件，则会提示错误。

In [36]:
# 不满足拆分条件
np.split(a, 3)

ValueError: array split does not result in an equal division

In [130]:
# 也可以为 1，那结果就还是自己
np.split(a, 1)

[array([[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12],
        [13, 14, 15, 16]], dtype=int32)]

`np.vsplit` 和 `np.split(..., aixs=0)` 是等价的，所以我们只要掌握 `np.split` 这个 API 就好。

In [134]:
np.vsplit(a, 2)

[array([[1, 2, 3, 4],
        [5, 6, 7, 8]], dtype=int32),
 array([[ 9, 10, 11, 12],
        [13, 14, 15, 16]], dtype=int32)]

### 合并

「❓」先思考给定两个 array 要满足什么条件才能合并？有几种合并方式？

`np.concatenate` 接受

- 一组 array
- 维度
- 目标 array，大小符合时，会被合并后的结果覆盖掉

In [152]:
a = np.arange(1, 13, dtype=np.int32).reshape(3, 4)
b = np.arange(-13, -1, dtype=np.int32).reshape(3, 4)

In [170]:
a, b

(array([[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12]], dtype=int32),
 array([[-13, -12, -11, -10],
        [ -9,  -8,  -7,  -6],
        [ -5,  -4,  -3,  -2]], dtype=int32))

In [153]:
base = np.arange(24).reshape(6, 4)
base

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [154]:
np.concatenate((a, b), axis=0, out=base)

array([[  1,   2,   3,   4],
       [  5,   6,   7,   8],
       [  9,  10,  11,  12],
       [-13, -12, -11, -10],
       [ -9,  -8,  -7,  -6],
       [ -5,  -4,  -3,  -2]])

In [155]:
np.concatenate((a, b), axis=1, out=base)

ValueError: Output array is the wrong shape

`np.vstack` 和 `np.hstack` 是 `np.concatenate` 在不同维度的快捷方式，我们只需记住一个就好。

In [157]:
np.vstack((a, b))

array([[  1,   2,   3,   4],
       [  5,   6,   7,   8],
       [  9,  10,  11,  12],
       [-13, -12, -11, -10],
       [ -9,  -8,  -7,  -6],
       [ -5,  -4,  -3,  -2]], dtype=int32)

In [158]:
np.hstack((a, b))

array([[  1,   2,   3,   4, -13, -12, -11, -10],
       [  5,   6,   7,   8,  -9,  -8,  -7,  -6],
       [  9,  10,  11,  12,  -5,  -4,  -3,  -2]], dtype=int32)

除了 `concatenate` 外，还有一个 `np.stack` 表示「堆叠」，它们的区别是堆叠会在对应的维度上增加维度（毕竟是拼起来的嘛）。两个API的参数是一样的。

In [162]:
np.stack((a, b))

array([[[  1,   2,   3,   4],
        [  5,   6,   7,   8],
        [  9,  10,  11,  12]],

       [[-13, -12, -11, -10],
        [ -9,  -8,  -7,  -6],
        [ -5,  -4,  -3,  -2]]], dtype=int32)

In [163]:
_.shape

(2, 3, 4)

In [164]:
np.stack((a, b), axis=1)

array([[[  1,   2,   3,   4],
        [-13, -12, -11, -10]],

       [[  5,   6,   7,   8],
        [ -9,  -8,  -7,  -6]],

       [[  9,  10,  11,  12],
        [ -5,  -4,  -3,  -2]]], dtype=int32)

In [165]:
_.shape

(3, 2, 4)

In [168]:
np.stack((a, b), axis=2)

array([[[  1, -13],
        [  2, -12],
        [  3, -11],
        [  4, -10]],

       [[  5,  -9],
        [  6,  -8],
        [  7,  -7],
        [  8,  -6]],

       [[  9,  -5],
        [ 10,  -4],
        [ 11,  -3],
        [ 12,  -2]]], dtype=int32)

In [169]:
_.shape

(3, 4, 2)

### 缺失值处理

缺失值表示对应位置「没有值」，在NumPy中以 `np.nan` 表示，它是一个浮点数。

In [176]:
a = np.array([1, np.nan], dtype=np.int32)

ValueError: cannot convert float NaN to integer

In [182]:
a = np.array([[np.nan, 1., 2.], [3., np.nan, 4.]], dtype=np.float32)
a

array([[nan,  1.,  2.],
       [ 3., nan,  4.]], dtype=float32)

如果数组里有缺失值，在相加（以及其他运算）的时候会直接等于 `np.nan`：

In [183]:
np.sum(a)

nan

但如果某一列或某一行没有 `np.nan`，则会输出正常值：

In [190]:
np.sum(a, axis=0)

array([nan, nan,  6.], dtype=float32)

要想忽略缺失值，可以使用索引替换，或直接使用 `np.nan<oper>` API，<oper> 表示运算，比如：`sum`，`max` 等。

In [191]:
np.nansum(a)

10.0

In [192]:
np.nanmax(a)

4.0

### 修改形状

这个我们刚刚其实一直在用，有两个接口：`np.reshape` 和 `np.resize`。后者是 in-place 的，在新的 shape 无法被满足时，会使用 0 填充，或截断。

In [203]:
a = np.arange(8)
a.resize(4, 2)

In [204]:
a

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7]])

In [205]:
b = np.arange(8)
b.resize(2, 3)

In [206]:
b

array([[0, 1, 2],
       [3, 4, 5]])

In [207]:
c = np.arange(8)
c.resize(2, 5)

In [208]:
c

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 0, 0]])

In [213]:
a = np.arange(8)
a.reshape(2, 3)

ValueError: cannot reshape array of size 8 into shape (2,3)

### 轴的调换

调换一个数组的两个轴。

In [235]:
x = np.arange(24).reshape(2, 3, 4)

In [236]:
x.swapaxes(0, 1).shape

(3, 2, 4)

In [237]:
x.swapaxes(0, 2).shape

(4, 3, 2)

看个小例子：

In [239]:
x = np.arange(12).reshape(3, 4)
x

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [240]:
x.swapaxes(0, 1)

array([[ 0,  4,  8],
       [ 1,  5,  9],
       [ 2,  6, 10],
       [ 3,  7, 11]])

超出数据维度的范围，无法交换：

In [247]:
x.swapaxes(0, 2)

AxisError: axis2: axis 2 is out of bounds for array of dimension 2

### 修改数据类型

这里修改数据类型指的不是修改array元素的数据类型，而是对array进行转换。

In [249]:
a = np.arange(6).reshape(2,3)
a

array([[0, 1, 2],
       [3, 4, 5]])

In [251]:
# 转换成Python数组
a.tolist()

[[0, 1, 2], [3, 4, 5]]

In [253]:
# 打平数组
a.flatten()

array([0, 1, 2, 3, 4, 5])

### 拷贝

主要包括 copy 和 view，上面有提到过一点，view 主要是在一个 `base` 上进行各种 shape 的变换；而 copy 则是重新复制一份数据。

In [258]:
a = np.arange(6).reshape(2, 3)

In [262]:
# b 是一个 view
b = a

In [263]:
np.shares_memory(a, b)

True

In [264]:
c = a.copy()

In [265]:
np.shares_memory(a, c)

False

### 排序

主要包括两个 API：`np.sort` 和 `np.argsort`，前者返回元素排序后的结果，后者则返回对应的 index。

它们都接受四个参数：

- 数组
- 对应的维度方向
- 排序算法，默认快排
- 顺序，当数组有多个领域（结构化数组）时，这个参数指定那个字段先比较

In [269]:
rng = np.random.default_rng()

In [272]:
arr = rng.integers(1, 100, (2, 3))
arr

array([[56, 57, 91],
       [52, 43, 41]])

In [274]:
# 按列排序
np.sort(arr, 0)

array([[52, 43, 41],
       [56, 57, 91]])

In [275]:
# 按行
np.sort(arr, 1)

array([[56, 57, 91],
       [41, 43, 52]])

In [279]:
# 默认按最后一个维度的
np.sort(arr)

array([[56, 57, 91],
       [41, 43, 52]])

接下来是对应的index：

In [281]:
np.argsort(arr)

array([[0, 1, 2],
       [2, 1, 0]])

In [282]:
np.argsort(arr, 0)

array([[1, 1, 1],
       [0, 0, 0]])