In [2]:
import numpy as np

### np.arange

`np.arange` 与 Python 的 `range` 用法一样，都用来创建一维数组。

接口参数：`[start], stop, [step]`，方括号里的是可选参数，默认值分别是 0 和 1。

In [35]:
[v for v in range(10)]

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [9]:
# 只有 stop
np.arange(5)

array([0, 1, 2, 3, 4])

In [10]:
# 指定 start, stop
np.arange(2, 5)

array([2, 3, 4])

In [11]:
# 指定 start, stop, step
np.arange(2, 5, 2)

array([2, 4])

### reshape

如果我们想创建一个多维数组，则需要将刚刚创建的一维数组 `reshape` 成多维。  
`reshape` 中元素数量乘积（元素总数）必须与一维向量元素数量相等。


注：在线性代数中一般一维数组=向量；二维数组=矩阵；三维+数组=张量。

In [12]:
# reshape 成 2 行 5 列的二维数组
np.arange(10).reshape(2, 5)

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [13]:
# reshape 成 2×2×3 的三维数组
np.arange(12).reshape(2, 2, 3)

array([[[ 0,  1,  2],
        [ 3,  4,  5]],

       [[ 6,  7,  8],
        [ 9, 10, 11]]])

In [14]:
# reshape 的 shape 中数字的乘积（元素数量）必须与一维向量元素数量相等
np.arange(10).reshape(3, 3)

ValueError: cannot reshape array of size 10 into shape (3,3)

### np.array

创建 `ndarray` 的快捷接口，接受一个 object，可以是：

- 一个 List
- 一个 Tuple
- 一个 List 的 Tuple
- 一个嵌套的 List

In [16]:
# list
np.array([1, 2])

array([1, 2])

In [20]:
# tuple
np.array((1, 2))

array([1, 2])

In [18]:
# list tuple
np.array([
    (1, 2, 3),
    (4, 5, 6)
])

array([[1, 2, 3],
       [4, 5, 6]])

In [19]:
# list list
np.array([
    [1, 2, 3],
    [4, 5, 6]
])

array([[1, 2, 3],
       [4, 5, 6]])

### np.ones/zeros

快速创建全 1 或全 0 的数组，可以指定 `shape`。

注意：创建的数字默认是 `float` 类型。

In [22]:
np.ones((2, 2, 2))

array([[[1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.]]])

In [25]:
np.zeros((1, 3, 1, 3))

array([[[[0., 0., 0.]],

        [[0., 0., 0.]],

        [[0., 0., 0.]]]])

### np.full

快速创建一个给定 shape 和填充值的数组。

注意：给定的填充值 shape 需要与给定的 shape 对应。参数 `shape` 是一个 tuple。

In [44]:
# 最简单的，给定 fill 是一个值
np.full((2, 3), 2)

array([[2, 2, 2],
       [2, 2, 2]])

In [46]:
# 如果 fill 是一个向量，那长度必须和 shape 的最后一维相等
np.full((2, 3), [1, 2, 3]), np.full((1, 2, 3), [1, 2, 3])

(array([[1, 2, 3],
        [1, 2, 3]]),
 array([[[1, 2, 3],
         [1, 2, 3]]]))

In [53]:
# 否则会提示错误
try:
    np.full((2, 2), [1, 2, 3])
except Exception as e:
    print(e)

could not broadcast input array from shape (3,) into shape (2,2)


如果 fill 是多维数组：

- shape 必须在行或列上与给定的 shape 对应，另一个维度为 1
- 或者与给定 shape 完全一致

否则会提示上面的错误。

In [58]:
fill = [[4], [3]]
# 2 行
np.full((2, 3), fill), np.full((2, 2), fill)

(array([[4, 4, 4],
        [3, 3, 3]]),
 array([[4, 4],
        [3, 3]]))

In [59]:
fill = [[3, 4, 5]]
# 或者 3 列
np.full((2, 3), fill)

array([[3, 4, 5],
       [3, 4, 5]])

In [72]:
fill = [[1, 2, 3], [4, 5, 6]]
# 或者一致
np.full((2, 3), fill)

array([[1, 2, 3],
       [4, 5, 6]])

### 指定类型

一般创建数组时不需要指定类型。但如果需要制定，建议「显式」地指定。

In [68]:
# 指定为 int8 类型
np.array([2, 3], np.int8)

array([2, 3], dtype=int8)

In [61]:
# 指定为 float16 类型
np.arange(8, dtype=np.float16).reshape(2, 4)

array([[0., 1., 2., 3.],
       [4., 5., 6., 7.]], dtype=float16)

In [64]:
# 常见的整型
np.int8, np.int16, np.int32, np.int64

(numpy.int8, numpy.int16, numpy.int32, numpy.int64)

In [65]:
# 常见的浮点精度
np.float16, np.float32, np.float64

(numpy.float16, numpy.float32, numpy.float64)

### 练习题

- 请尝试创建一个从 0-50 所有奇数构成的 5×5 二维数组
- 请尝试创建一个 5×5 的二维数组，每一行所有元素分别是 1 2 3 4 5
- 请尝试让 full 指定的 shape 与给定的填充值 shape 不一致并查看错误提示
- 请尝试用不同的数据类型创建数组，并使用 `nbytes` 方法查看数组大小

In [74]:
np.arange(1, 51, 2).reshape(5, 5)

array([[ 1,  3,  5,  7,  9],
       [11, 13, 15, 17, 19],
       [21, 23, 25, 27, 29],
       [31, 33, 35, 37, 39],
       [41, 43, 45, 47, 49]])

In [76]:
np.full((5, 5), [[1], [2], [3], [4], [5]])

array([[1, 1, 1, 1, 1],
       [2, 2, 2, 2, 2],
       [3, 3, 3, 3, 3],
       [4, 4, 4, 4, 4],
       [5, 5, 5, 5, 5]])

In [77]:
snp.full((2, 3), [[1,2], [2,3]])

ValueError: could not broadcast input array from shape (2,2) into shape (2,3)