In [ ]:
# 安装watermark
!pip install watermark

In [3]:
%load_ext watermark

In [4]:
%watermark

Last updated: 2022-01-15T17:41:06.935579+08:00

Python implementation: CPython
Python version       : 3.8.10
IPython version      : 7.23.1

Compiler    : Clang 11.0.0 (clang-1100.0.33.17)
OS          : Darwin
Release     : 21.1.0
Machine     : x86_64
Processor   : i386
CPU cores   : 4
Architecture: 64bit



In [1]:
import numpy as np

In [6]:
%watermark --iversions

numpy: 1.19.5



文档阅读说明：

- 🐧 表示 Tip
- ⚠️ 表示注意事项

## 常量

NumPy 中自带一部分常用的常量，方便直接使用。

### 特殊值

In [5]:
# 自然对数
np.e

2.718281828459045

In [12]:
# PI
np.pi

3.141592653589793

In [96]:
# 0
np.PZERO

0.0

In [97]:
# -0
np.NZERO

-0.0

In [102]:
# None
np.newaxis

### 空值

In [13]:
# 空值
np.nan

nan

In [39]:
type(np.nan)

float

注意，`np.nan` 是一个值，两个 `np.nan` 不相等，虽然它们同属于一个类型。

In [17]:
np.nan is np.nan

True

In [18]:
np.nan == np.nan

False

可以使用 `np.isnan` 方法进行判断。

In [34]:
np.isnan(1), np.isnan(2.0), np.isnan(np.nan), np.isnan(np.log(-10.))

<ipython-input-34-1060db748605>:1: RuntimeWarning: invalid value encountered in log
  np.isnan(1), np.isnan(2.0), np.isnan(np.nan), np.isnan(np.log(-10.))


(False, False, True, True)

In [71]:
# 以下等价
np.nan is np.NAN is np.NaN

True

### 无穷

In [83]:
# 正无穷
np.inf

inf

In [87]:
# 负无穷
np.NINF == -np.inf

True

In [38]:
type(np.inf)

float

In [93]:
np.log(0)

<ipython-input-93-f6e7c0610b57>:1: RuntimeWarning: divide by zero encountered in log
  np.log(0)


-inf

In [42]:
-np.inf < -100

True

In [43]:
np.inf < 10

False

可以使用 `np.isxx` 进行判断。

In [76]:
# 是否正或负去穷
np.isinf(-np.inf)

True

In [77]:
# 哪些元素正无穷
np.isposinf(-np.inf)

False

In [78]:
# 哪些元素负无穷
np.isneginf(np.inf)

False

In [79]:
# 哪些元素有限的（不是非数字、正无穷或负无穷）
np.isfinite(3)

True

In [82]:
np.isfinite(np.inf)

False

In [98]:
# 以下几个方法等价
np.inf == np.Inf == np.Infinity == np.infty == np.PINF 

True

## 数据类型


numpy 支持丰富的数据类型，[官方文档](https://numpy.org/devdocs/user/basics.types.html)中介绍的非常全面。这里我们不要陷入太多纠结，尝试从整体的角度重新梳理一遍。其实我们更需要关注的应该是其内置的数据类型对象 `dtype`，也就是这个文档：[Data type objects](https://numpy.org/devdocs/reference/arrays.dtypes.html#arrays-dtypes)。

In [73]:
# 数据类型 和 数据类型对象
type(np.int8), type(np.dtype(np.int8))

(type, numpy.dtype)

数据类型对象描述了如何解释与数组项对应的固定大小的内存块中的字节。主要包括以下几个方面（当然有很多其他信息）：

- 数据类型
- 数据大小
- 数据的顺序
- 如果是「结构化数据类型」则是其他数据类型的集合
- 如果数据类型是子数组，它的形状和数据类型


之前咱们创建 array 的时候都没有关心过数据类型，这种情况下，numpy 会自动匹配当前输入最合适的数据类型，并将其 cast 到所有元素。


总的来说可以大致分成以下几种，而我们绝大多数情况下最应该关注的其实就是 int 和 float 这两种：

- bool：`bool8`, `bool_`，不是 int
- int：`int8/byte`, `int16/short`, `int32`, `int64/longlong`, `int_`
- uint：无符号类型，表示 `unsigned`，对应 int
- float：`float16/half`, `float32/single`, `float64/double`, `float_`
- complex：复数，`complex64`, `complex128`, `complex_`
- str：`str0`, `str_`，表示 unicode 编码
- bytes: `bytes_`, `string_`
- datetime/timedelta
- structed array

后面的数字表示一个数字在内存中占几位，**一般比较推荐使用这种表示**；带下划线的表示 python 的数据类型，numpy 可以自动将 python 的类型转为它；此外，浮点数还支持不同精度以及扩展精度。

### 类型

首先看这个图：

![](https://numpy.org/devdocs/_images/dtype-hierarchy.png)

来自：[Scalars — NumPy v1.23.dev0 Manual](https://numpy.org/devdocs/reference/arrays.scalars.html)

基本涵盖了上面除 datetime 和 structed array 之外的所有类型，这两种类型我们后面单独来说。

In [592]:
# 直观验证上图的关系
(
    isinstance(np.str_(), np.flexible),
    isinstance(np.bytes_(), np.flexible),
    isinstance(np.void(b""), np.flexible),
    
    isinstance(np.int_(), np.integer),
    isinstance(np.float_(), np.floating),
    isinstance(np.complex_(), np.complexfloating)
)

(True, True, True, True, True, True)

In [557]:
# 很多类型都有 alias，它们其实是一回事
(
    np.longlong is np.int64, np.short is np.int16, np.byte is np.int8,
    # 不同精度
    np.half is np.float16, np.single is np.float32, np.double is np.float64,
    # 扩展精度
    np.longfloat is np.longdouble,
    # 字符串
    np.unicode_ is np.str_,
    # bytes
    np.bytes_ is np.string_
)

(True, True, True, True, True, True, True, True, True)

In [454]:
# python 内置类型
(
    np.bool_ is np.bool8, 
    np.int_ is np.int32,
    np.float_ is np.float64,
    np.str_ is np.str0,
    np.complex_ is np.complex128
)

(True, True, True, True, True)

接下来以整型为例来说明，其他的类似。

In [456]:
# 创建一个「数据类型对象」
# 如果使用 python 的类型，会自动识别支持，不过建议使用 numpy 的 dtype 类型指定类型
i32 = np.dtype("int")
i32

dtype('int32')

In [447]:
# numpy 支持的 python 类型
np.int_, np.float_, np.bool_, np.complex_, np.str_

(numpy.int32, numpy.float64, numpy.bool_, numpy.complex128, numpy.str_)

In [445]:
# 比较推荐这样创建
i32 = np.dtype(np.int32)
i32

dtype('int32')

Tips：建议在创建 array 时指定数据类型，且使用统一的数据类型计算。

In [21]:
%timeit np.arange(100, dtype=np.float32).reshape(10, 10) * np.arange(100, dtype=np.int32).reshape(10, 10)

27 µs ± 1.51 µs per loop (mean ± std. dev. of 7 runs, 10000 loops each)


In [20]:
%timeit np.arange(100, dtype=np.int32).reshape(10, 10) * np.arange(100, dtype=np.int32).reshape(10, 10)

19.9 µs ± 2.4 µs per loop (mean ± std. dev. of 7 runs, 10000 loops each)


### 大小

类型暂时先看到这儿，先来看看大小：

In [302]:
# int 默认 32 位
arr = np.array([2**31-1])
arr.dtype

dtype('int32')

In [275]:
# 每个数字 4 bytes = 32 bits
arr.nbytes

4

In [277]:
bytes(arr)

b'\xff\xff\xff\x7f'

In [276]:
list(map(hex, arr))

['0x7fffffff']

In [289]:
15 *(16**0+16**1+16**2+16**3+16**4+16**5+16**6) + 7*16**7 == 2 ** 31 - 1

True

In [282]:
# 超出32位表示的范围，自动用64位
arr = np.array([2**31])
arr.dtype

dtype('int64')

In [283]:
# 一共是 8 个字节（Byte），64 位（bit）
arr.nbytes

8

In [284]:
bytes(arr)

b'\x00\x00\x00\x80\x00\x00\x00\x00'

In [285]:
list(map(hex, arr))

['0x80000000']

In [286]:
8 * 16**7  == 2 ** 31

True

In [475]:
# 可以使用 iinfo 查看
np.iinfo(np.int32)

iinfo(min=-2147483648, max=2147483647, dtype=int32)

In [495]:
# finfo 查看 float
np.finfo(np.float64)

finfo(resolution=1e-15, min=-1.7976931348623157e+308, max=1.7976931348623157e+308, dtype=float64)

### 顺序

这个看起来就不那么直观了。咱们先了解下背景知识。

字节顺序（Endianness）在计算机科学中指内存中字节的排列顺序。字节的排列有两个通用规则：

- 将低位放在较小的地址处，高位放在较大的地址处，称为小端序（little-endian）。
- 与上面相反的就是大端序（big-endian）。


![](https://qnimg.lovevivian.cn/cs-endian-1.jpg)

图片来自：[Endianness - Wikipedia](https://en.wikipedia.org/wiki/Endianness)


我们常用的 x86 计算机是小端位，因为内存地址一般是从低到高逐渐增加的，而我们的二进制（或者其他进制）是高位在前，低位在后，这样用小端序就会很自然，也便于编程。不过刚好人读起来正好是反着的。

拿上面的图片为例，0A0B0C0D 是自然顺序，0D 是低位，在小端序中就被放在了低地址；0A 是高位，在大端序中被放在低位。


在 `numpy` 中，dtype 的每个类型都可以用一个字符表示，而使用字符表示时，可以增加字节序。

支持的字符表示如下（大小写分别表示无符号和有符号）：


Format | C Type | Python Type | Standard Size 
-------|--------|-------------|--------------
`?`    | `_Bool`| `bool`      | 1
`b/B`  | `char` | `int`       | 1
`h/H`  | `short`| `int`       | 2
`i/I`  | `int`  | `int`       | 4
`l/L`  | `long` | `int`       | 4
`q/Q`  | `long long` | `int`  | 8
`e`    | `half`   | `float`   | 2
`f`    | `float` | `float`    | 4
`d`    | `double` | `float`   | 8


另外还有几个复杂类型：

- `c`：复数浮点
- `m/M`: timedelta / datetime
- `O`: Python 对象
- `U`: Unicode 字符串
- `V`: void
- `S/a`: 零终止字节（不推荐）

而字节序共有以下几种：

Character | Byte order | Size 
-----------|-----------|-------
`=`       | native     | standard
`<`       | little-endian     | standard
`>`       | big-endian     | standard

默认是 `=`。

上面部分参考自：https://docs.python.org/3/library/struct.html

In [629]:
# 比如以下表示 小端序 int 类型
np.dtype("<i") == np.dtype(np.int32)

True

In [671]:
np.dtype('l') == np.dtype('i')

True

In [666]:
# 默认 =
np.dtype(np.int32).byteorder

'='

In [31]:
# 也可以显式指定长度
# U 可以是任意长度
np.dtype('<i4'), np.dtype('=f8'), np.dtype('<U3')

(dtype('int32'), dtype('float64'), dtype('<U3'))

In [42]:
# 以 01 03 为例（十进制 259，16x16+3），二者顺序相反
# 从左到右地址由低到高，因为是 16 进制，所以正好是 32 位
bytes(np.array([259], dtype="<i2")), bytes(np.array([259], dtype=">i2"))

(b'\x03\x01', b'\x01\x03')

字节顺序常用于不同设备（字节序不同）之间数据交互，也可以互相转换。

### 结构化

结构化数组就是数据类型是**一组**（而不是只有一个）不同的类型的数组。

In [4]:
arr = np.array(
    [('Rex', 9, 81.0), ('Fido', 3, 27.0)],
    dtype=[('name', 'U10'), ('age', 'i4'), ('weight', 'f4')]
)
arr

array([('Rex', 9, 81.), ('Fido', 3, 27.)],
      dtype=[('name', '<U10'), ('age', '<i4'), ('weight', '<f4')])

In [5]:
arr.shape

(2,)

如果我们去掉 `dtype`，就和之前介绍的一样了：

In [6]:
np.array(
    [('Rex', 9, 81.0), ('Fido', 3, 27.0)])

array([['Rex', '9', '81.0'],
       ['Fido', '3', '27.0']], dtype='<U32')

因为每个元素都是「结构化」的数据，所以也叫结构化数组。

⚠️ 注意：`dtype` 的每一个 tuple 对应元素中的一个元素。比如上面的例子中，第一个元素是 U10 类型，表示的是每一个 tuple 的第一个元素是 U10 类型；另外，相比您也发现了，结构化数组都是一维的。

In [11]:
arr[0]

('Rex', 9, 81.)

In [8]:
np.array([(1, 2, 5), (4, 5, 7), (7, 8 ,11), (10, 11, 12)],
             dtype=[('x', 'i4'), ('y', 'f4'), ('z', 'f8')])

array([( 1,  2.,  5.), ( 4,  5.,  7.), ( 7,  8., 11.), (10, 11., 12.)],
      dtype=[('x', '<i4'), ('y', '<f4'), ('z', '<f8')])

### 时间

## 数组对象

### ndarray

NumPy 提供了一个 N 维数组类型，即 `ndarray`，描述了**相同类型**「元素」集合。它是偏底层的 array 接口。

所有的 `ndarray` 元素都是同质的，每个元素占用大小相同的内存块，具体大小由「数据类型」决定。`ndarray` 可以共享相同数据。

对象签名如下：

```python
numpy.ndarray(shape, dtype=float, buffer=None, offset=0, strides=None, order=None)
```

- shape：整数元组，表示形状
- dtype：数据类型对象
- buffer：使用 buffer 中的数据填充 `ndarray`
- offset：buffer 中的偏移量
- stride：内存中数据跨度
- order：行为主（C-Style）或列为主（Fortran-Style）


当 buffer 为空时，shape, dtype 和 order 三个参数会被使用；  
当 buffer 不为空时，所有参数都会被使用。

In [358]:
# buffer 为空，结果随机
arr = np.ndarray(shape=(2, 3), dtype=np.int, order="C")
arr

array([[38203952,        0,        0],
       [       0,        0,        0]])

In [394]:
# buffer 不为空
buf = np.array([1, 2, 3, 4], dtype=np.int)
arr = np.ndarray(shape=(2, 2), 
                 dtype=np.int, 
                 offset=0,
                 buffer=buf,
                 strides=(np.int_().itemsize, np.int_().itemsize),
                 )
arr

array([[1, 2],
       [2, 3]])

In [398]:
# buf 的 shape 并无关系
buf = np.array([[[[1, 2]], [[3, 4]], [[5, 6]], [[7, 8]]]], dtype=np.int, order="C")
arr = np.ndarray(shape=(2, 2), 
                 dtype=np.int, 
                 offset=0,
                 buffer=buf,
                 strides=(np.int_().itemsize, np.int_().itemsize),
                 )
arr

array([[1, 2],
       [2, 3]])

In [399]:
# buf 的 order 有关，原因我们后面解释
buf = np.array([[[[1, 2]], [[3, 4]], [[5, 6]], [[7, 8]]]], dtype=np.int, order="F")
arr = np.ndarray(shape=(2, 2), 
                 dtype=np.int, 
                 offset=0,
                 buffer=buf,
                 strides=(np.int_().itemsize, np.int_().itemsize),
                 )
arr

array([[1, 3],
       [3, 5]])

由于我们平时很少用到这个接口，您可能会对其中的一些参数有些困惑。接下来我们稍微解释一下。buffer 为空时没有太多要强调的，重点说一下 buffer 不为空时。

`shape` 和 `dtype` 也比较清晰，`buffer` 刚刚也说明了，使用一位数组即可。主要是剩下的三个参数：`offset`, `strides` 和 `order`。

`order` 是指采用哪种风格进行存储。计算中，行主序（C Style）和列主序（F Style）是将多维数组存储在线性存储器（例如 RAM）中的方法。在行主序中，一行的连续元素彼此相邻，而在列主序中，一列连续元素彼此相邻。具体可参考：[Row- and column-major order - Wikipedia](https://en.wikipedia.org/wiki/Row-_and_column-major_order)。

**需要注意的是**：不同的存储方式会导致计算效率的不同，可以针对具体的场景（处理行多还是列多）选择不同的 Style。

In [387]:
# copy 让 carr 拥有数据，否则只是 view
carr = np.arange(1000000).reshape(1000, 1000).copy()
carr.flags

  C_CONTIGUOUS : True
  F_CONTIGUOUS : False
  OWNDATA : True
  WRITEABLE : True
  ALIGNED : True
  WRITEBACKIFCOPY : False
  UPDATEIFCOPY : False

In [388]:
farr = np.asfortranarray(carr)
farr.flags

  C_CONTIGUOUS : False
  F_CONTIGUOUS : True
  OWNDATA : True
  WRITEABLE : True
  ALIGNED : True
  WRITEBACKIFCOPY : False
  UPDATEIFCOPY : False

In [389]:
# 加第一行所有列
# C style 应该比 F style 快一些
%timeit np.sum(carr[0,:])

6.8 µs ± 255 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)


In [390]:
%timeit np.sum(farr[0,:])

9.63 µs ± 234 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)


In [391]:
# 加第一列所有行
# F style 应该比 C style 快一些
%timeit np.sum(farr[:, 0])

6.76 µs ± 151 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)


In [392]:
%timeit np.sum(carr[:, 0])

9.69 µs ± 447 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)


`offset` 和 `strides` 是配合使用的，前者是偏移位置，后者是步幅，它必须与 shape 等长。也就是根据给定的 buffer，生成目标 shape 的 array。至于这么做的原因，主要是和内部存储有关，事实上，`ndarray` 就是通过这两个参数来控制 shape，不同的 shape 其实存储是一样的。

In [526]:
buf = np.arange(1, 9)
buf

array([1, 2, 3, 4, 5, 6, 7, 8])

In [532]:
# 因为咱们是 int64，所以 1 个数字是 64 位，即 8 个 Bytes
buf.strides

(8,)

In [528]:
# 这个例子 偏移了「1」个数字，步幅也正好是「1」
# 结果是 从 2 开始
# strides 两个数字分别控制 行和列 的步幅：从左往右看，每次增加 1 个数字，从上往下看，每次增加 1 个数字
arr1 = np.ndarray(
    shape=(2, 3), 
    dtype=np.int8, 
    offset=8,
    buffer=buf,
    strides=(8, 8),
    order="C")
arr1

array([[2, 3, 4],
       [3, 4, 5]], dtype=int8)

In [530]:
# 再来个例子
# 没有偏移，ok，从 1 开始
# 从左到右是列，每次加 1 个数字，从上到下是行，每次增加 2 个数字
arr2 = np.ndarray(
    shape=(3, 2), 
    dtype=np.int8, 
    offset=0,
    buffer=buf,
    strides=(16, 8),
    order="C")
arr2

array([[1, 2],
       [3, 4],
       [5, 6]], dtype=int8)

ok，接下来，我们看一下不同的 shape 的存储情况。

In [537]:
buf = np.arange(1, 9, dtype=np.int8)
buf

array([1, 2, 3, 4, 5, 6, 7, 8], dtype=int8)

In [538]:
# int8 的，每次正好 8 位，即 1 个 Byte
buf.strides

(1,)

In [539]:
bytes(buf)

b'\x01\x02\x03\x04\x05\x06\x07\x08'

In [540]:
# 改一下 shape
buf.shape = 2, 4

In [542]:
buf.strides

(4, 1)

In [541]:
# 发现规律了吗？
buf

array([[1, 2, 3, 4],
       [5, 6, 7, 8]], dtype=int8)

In [544]:
# 此时再看 内存布局
# 和之前是一样的，也就是说，用 strides 我们就可以给同一个 array 不同的 shape
bytes(buf)

b'\x01\x02\x03\x04\x05\x06\x07\x08'

事实上，无论 shape 怎么变化，内存是完全没变化的，不同的 array 其实就是不同的 strides 方式而已。感兴趣的可以进一步尝试。

另外，使用 buffer 创建的 `ndarray` 都使用了同一块内存。

In [565]:
buf = np.arange(1, 9, dtype=np.int8)

In [566]:
arr1 = np.ndarray(
    shape=(2, 3), 
    dtype=np.int8, 
    offset=0,
    buffer=buf,
    strides=(1, 1),
    order="C")
arr1

array([[1, 2, 3],
       [2, 3, 4]], dtype=int8)

In [567]:
arr2 = np.ndarray(
    shape=(3, 2), 
    dtype=np.int8, 
    offset=0,
    buffer=buf,
    strides=(1, 1),
    order="C")
arr2

array([[1, 2],
       [2, 3],
       [3, 4]], dtype=int8)

In [574]:
bytes(arr1), bytes(arr2)

(b'\x01\x02\x03\x02\x03\x04', b'\x01\x02\x02\x03\x03\x04')

In [575]:
np.may_share_memory(arr1, arr2), np.may_share_memory(buf, arr1)

(True, True)

其实，无论 arr1 还是 arr2 都是 buf 的一个 view（引用），与此相对的是 copy。一般来说，切片（slicing）会创建 view，索引（indexing）会创建 copy。我们在后面的内容会进一步解释。

也就是说，使用 buffer 创建 `ndarray` 其实可以理解成一种「切片」。实际上，如果您查看 `np.array` 的接口，就会发现其中有个 `copy` 参数，它默认是 `True`。

In [579]:
buf, arr1, arr2

(array([1, 2, 3, 4, 5, 6, 7, 8], dtype=int8),
 array([[1, 2, 3],
        [2, 3, 4]], dtype=int8),
 array([[1, 2],
        [2, 3],
        [3, 4]], dtype=int8))

In [580]:
buf[0] = 9

In [581]:
buf, arr1, arr2

(array([9, 2, 3, 4, 5, 6, 7, 8], dtype=int8),
 array([[9, 2, 3],
        [2, 3, 4]], dtype=int8),
 array([[9, 2],
        [2, 3],
        [3, 4]], dtype=int8))

`strides`　不同时，处理的效率也有差异。当步长增加时，找到对应位置的值会变慢。其原因是，CPU 在处理任务时会将数据从内存读取到缓存，步长小时，需要的传输更少。比如要取 10 个数，连在一起的（步长=1个数字）可以一次取到，但步长大时却要取多次。

>注：CPU 缓存是用于减少处理器访问内存所需平均时间的部件。在金字塔式存储体系中它位于自顶向下的第二层，仅次于 CPU 寄存器。其容量远小于内存，但速度却可以接近处理器的频率。一般会有多级缓存。——维基百科

In [628]:
arr1 = np.ones((1000, 100), dtype=np.int8)
arr2 = np.ones((10000, 100), dtype=np.int8)[::10]
arr1.shape, arr2.shape

((1000, 100), (1000, 100))

In [639]:
arr1.flags

  C_CONTIGUOUS : True
  F_CONTIGUOUS : False
  OWNDATA : True
  WRITEABLE : True
  ALIGNED : True
  WRITEBACKIFCOPY : False
  UPDATEIFCOPY : False

In [638]:
# OWNDATA=False，意思是这个 array 的数据是从其他地方「借」来的
# 从哪个地方呢？当然就是 `np.ones((10000, 100), dtype=np.int8)` 这里了
arr2.flags

  C_CONTIGUOUS : False
  F_CONTIGUOUS : False
  OWNDATA : False
  WRITEABLE : True
  ALIGNED : True
  WRITEBACKIFCOPY : False
  UPDATEIFCOPY : False

In [631]:
np.any(arr1 == arr2)

True

In [632]:
arr1.strides, arr2.strides

((100, 1), (1000, 1))

In [633]:
%timeit arr1.sum()

673 µs ± 23.5 µs per loop (mean ± std. dev. of 7 runs, 1000 loops each)


In [634]:
%timeit arr2.sum()

785 µs ± 8.11 µs per loop (mean ± std. dev. of 7 runs, 1000 loops each)


最后说明下，我们上面的例子都是用 `int` 类型来说明，其他数据类型类似。

另外，源码中的大致逻辑是：`arrayobject.c` 中的 `array_new` 方法调用了 ctors.c 中的 `PyArray_NewFromDescr_int` 来实现创建一个 `ndarray`。

除了上面提到的可以影响性能，其实不同的调用接口也是有差异的。比如转置操作，一共有三种方法：

- `arr.T`
- `arr.transpose`
- `np.transpose`

其实它们几乎是一样的，只是调用方式不同，性能也表现出不同的差异（很自然嘛）。

In [378]:
rng = np.random.default_rng(42)

In [379]:
arr = rng.integers(0, 10, (2, 3))
arr

array([[0, 7, 6],
       [4, 4, 8]], dtype=int64)

In [373]:
%timeit arr.T

190 ns ± 8.08 ns per loop (mean ± std. dev. of 7 runs, 1000000 loops each)


In [374]:
%timeit arr.transpose()

211 ns ± 3.77 ns per loop (mean ± std. dev. of 7 runs, 1000000 loops each)


In [372]:
%timeit np.transpose(arr)

1.45 µs ± 131 ns per loop (mean ± std. dev. of 7 runs, 1000000 loops each)


稍微解释一下，`arr.T` 和 `arr.transpose` 是差不多的，后者稍微慢的原因是还有一个 `axes` 参数；而 `np.transpose` 慢则是因为它的调用方式：

```python
def transpose(a, axes=None):
    return _wrapfunc(a, 'transpose', axes)

def _wrapfunc(obj, method, *args, **kwds):
    try:
        return getattr(obj, method)(*args, **kwds)
    except (AttributeError, TypeError):
        return _wrapit(obj, method, *args, **kwds)
```

所以如果可以的话，推荐尽量在 array 上调用方法。

另外需要提醒的是，转置其实就是把 C-style 转成 F-style：

In [382]:
arr.flags

  C_CONTIGUOUS : True
  F_CONTIGUOUS : False
  OWNDATA : True
  WRITEABLE : True
  ALIGNED : True
  WRITEBACKIFCOPY : False
  UPDATEIFCOPY : False

In [384]:
arr.T.flags

  C_CONTIGUOUS : False
  F_CONTIGUOUS : True
  OWNDATA : False
  WRITEABLE : True
  ALIGNED : True
  WRITEBACKIFCOPY : False
  UPDATEIFCOPY : False

### array

首先要明确，`array` 只是快速创建 `ndarray` 的接口函数，源代码是 `core/src/multiarray/methods.c` 中的 `array_getarray`。这玩意儿其实就调用了上面提到的 `PyArray_NewFromDescr_int`。

## 小结


- `ndarray` 是基本的数组对象，它底层有两种存储方式（C Style 和 F Style），可以根据实际处理逻辑选择合适的方式。另外注意，切片后的引用，步长长的比步长短的处理起来要慢。

## 资料

- [What Is Little-Endian And Big-Endian Byte Ordering? | Engineering Education (EngEd) Program | Section](https://www.section.io/engineering-education/what-is-little-endian-and-big-endian/)