In [1]:
import numpy as np

In [33]:
arr = np.array([
    [0.123434343242999999999, 0.1234243242342342],
    [0.0134234234324, 0.234324324234114]
])
arr

array([[0.12343434, 0.12342432],
       [0.01342342, 0.23432432]])

In [34]:
arr.round(2)

array([[0.12, 0.12],
       [0.01, 0.23]])

In [36]:
np.around(arr, 2)

array([[0.12, 0.12],
       [0.01, 0.23]])

In [28]:
arr

array([[0.12343434, 0.12342432],
       [0.01342342, 0.23432432]])

In [29]:
np.float16(arr)

array([[0.1234 , 0.1234 ],
       [0.01342, 0.2344 ]], dtype=float16)

In [30]:
np.float32(arr)

array([[0.12343434, 0.12342432],
       [0.01342342, 0.23432432]], dtype=float32)

In [31]:
np.float64(arr)

array([[0.12343434, 0.12342432],
       [0.01342342, 0.23432432]])

In [45]:
x = 0.01
epsilon = 0.01 - np.float32(0.01)
arr = np.arange(x - 10*epsilon, x + 10*epsilon, epsilon).reshape(4, 5)
arr

array([[0.01, 0.01, 0.01, 0.01, 0.01],
       [0.01, 0.01, 0.01, 0.01, 0.01],
       [0.01, 0.01, 0.01, 0.01, 0.01],
       [0.01, 0.01, 0.01, 0.01, 0.01]])

In [62]:
np.float16(arr).tolist()

[[0.01000213623046875,
  0.01000213623046875,
  0.01000213623046875,
  0.01000213623046875,
  0.01000213623046875],
 [0.01000213623046875,
  0.01000213623046875,
  0.01000213623046875,
  0.01000213623046875,
  0.01000213623046875],
 [0.01000213623046875,
  0.01000213623046875,
  0.01000213623046875,
  0.01000213623046875,
  0.01000213623046875],
 [0.01000213623046875,
  0.01000213623046875,
  0.01000213623046875,
  0.01000213623046875,
  0.01000213623046875]]

In [58]:
np.float64(arr).round(2).tolist()

[[0.01, 0.01, 0.01, 0.01, 0.01],
 [0.01, 0.01, 0.01, 0.01, 0.01],
 [0.01, 0.01, 0.01, 0.01, 0.01],
 [0.01, 0.01, 0.01, 0.01, 0.01]]